[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "lexgraph_legal_rag"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
    "scikit-learn",
    "fastapi>=0.115",
    "httpx",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["lexgraph_legal_rag"]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
pythonpath = ["src"]
