{
  "groups": [
    {
      "name": "lexgraph_alerts",
      "rules": [
        {
          "alert": "HighErrorRate",
          "expr": "rate(http_requests_total{status=~\"5..\"}[5m]) > 0.1",
          "for": "5m",
          "labels": {
            "severity": "critical"
          },
          "annotations": {
            "summary": "High error rate detected",
            "description": "Error rate is above 10% for 5 minutes"
          }
        },
        {
          "alert": "HighResponseTime",
          "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2.0",
          "for": "10m",
          "labels": {
            "severity": "warning"
          },
          "annotations": {
            "summary": "High response times detected",
            "description": "95th percentile response time is above 2 seconds"
          }
        },
        {
          "alert": "HighMemoryUsage",
          "expr": "process_resident_memory_bytes > 2147483648",
          "for": "15m",
          "labels": {
            "severity": "warning"
          },
          "annotations": {
            "summary": "High memory usage detected",
            "description": "Memory usage is above 2GB for 15 minutes"
          }
        }
      ]
    }
  ]
}