apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bioneural-role
  namespace: bioneural-olfactory-fusion-production
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - configmaps
  verbs:
  - get
  - list
  - watch
