apiVersion: v1
kind: ConfigMap
metadata:
  name: lexgraph-config
  namespace: lexgraph
  labels:
    app.kubernetes.io/name: lexgraph-legal-rag
    app.kubernetes.io/component: config
data:
  ENVIRONMENT: "production"
  METRICS_PORT: "8001"
  LEGAL_CORPUS_PATH: "/app/data/legal_docs"
  # Add non-sensitive configuration here