{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "lexgraph-secrets"
  },
  "type": "Opaque",
  "data": {
    "api-key": "REPLACE_WITH_BASE64_ENCODED_API_KEY",
    "database-url": "REPLACE_WITH_BASE64_ENCODED_DATABASE_URL",
    "openai-api-key": "REPLACE_WITH_BASE64_ENCODED_OPENAI_KEY"
  }
}