name: Repository Hygiene Automation

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no changes made)'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: read

jobs:
  hygiene:
    name: GitHub Repository Hygiene
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hygiene_requirements.txt
          
      - name: Run hygiene bot (dry-run)
        if: github.event.inputs.dry_run == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.HYGIENE_BOT_TOKEN || secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
        run: |
          python3 github_hygiene_bot.py \
            --token "$GITHUB_TOKEN" \
            --owner "$GITHUB_OWNER" \
            --dry-run
            
      - name: Run hygiene bot
        if: github.event.inputs.dry_run != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.HYGIENE_BOT_TOKEN || secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
        run: |
          python3 github_hygiene_bot.py \
            --token "$GITHUB_TOKEN" \
            --owner "$GITHUB_OWNER"
            
      - name: Upload metrics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hygiene-metrics
          path: metrics/profile_hygiene.json
          retention-days: 30